version: "3.9"

services:
  backend-twitch:
    build: ./backend-twitch
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/vaarattu
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
