services:
  backend-twitch:
    build: ./backend-twitch
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
