services:
  backend-twitch:
    build:
      context: ./backend
      dockerfile: ./twitch/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/.env:/app/.env:ro
      - ./backend/twitch/tokens.bot.json:/app/tokens.bot.json
      - ./backend/twitch/tokens.streamer.json:/app/tokens.streamer.json
    restart: unless-stopped
    network_mode: "host"

  backend-web:
    build:
      context: ./backend
      dockerfile: ./web/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/.env:/app/.env:ro
    restart: unless-stopped
    network_mode: "host"

volumes:
  postgres_data:
