services:
  db-migrate:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: migrate
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: "no"
    network_mode: "host"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3002
    restart: unless-stopped
    network_mode: "host"

  backend-twitch:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: twitch
      args:
        SERVICE: twitch
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/.env:/app/.env:ro
      - ./backend/twitch/tokens.bot.json:/app/tokens.bot.json
      - ./backend/twitch/tokens.streamer.json:/app/tokens.streamer.json
    restart: unless-stopped
    network_mode: "host"

  backend-web:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: web
      args:
        SERVICE: web
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/.env:/app/.env:ro
    restart: unless-stopped
    network_mode: "host"
